### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by jhubert** [mike927/guard-slimlint#3]
Hi Mike,

Great to see #2 get merged in. Would it be possible to get a new Gem cut so that we can use this update without pointing to the master repo?

Thanks!

**Comment by jhubert** [comment]
Anything we can do to help here?

**Comment by mike927** [comment]
Hello @jhubert 
As You can see for some time I have not been maintaining this gem. However, it would be highly appreciated if you or someone take over this job.
Greetings!

**Comment by mike927** [comment]
I will release the new version of gem including your PR as soon as possible.

**Comment by jhubert** [comment]
Hi Mike,

I’d be happy to take it over if you’d like. Thanks for the reply.

Warmly,
Jeremy

**Comment by markedmondson** [comment]
Hey @mike927 - also happy to take it over if need be.

**Comment by mike927** [comment]
Hello guys @jhubert, @markedmondson. After a long time, a new gem version up to date with master branch has been released.
