### ISSUE TITLE
MacOS popup notifications support

### ISSUE THREAD

**Issue by mike927** [mike927/guard-slimlint#4]
Hello,
my first releases I tested on Linux distributions. Since that time I have been working on macOS. Can anyone else check not working popup notifications out for macOS?

**Comment by swrobel** [comment]
They are working fine for me with the latest release using `terminal-notifier-guard`
<img width="335" alt="Screen Shot 2019-08-26 at 12 13 12 PM" src="https://user-images.githubusercontent.com/157270/63716438-e5a41d00-c7fa-11e9-90ae-b39c777d7f28.png">
